"""
Static backtest/report artifact passthrough. Every file here is a batch
output produced offline by lstm.run_train/backtest.run_*.py -- these
endpoints load the file once, sanitize it, and cache the sanitized copy
in-process (functools.lru_cache); they never regenerate the artifact
on request.

The walk-forward endpoint injects an explicit `scope` field NOT present in
the source JSON, so the frontend cannot accidentally drop the caveat that
this is a semiconductors-only, 8-ticker, now-superseded-universe historical
finding (see the Phase H plan section on stale walk-forward checkpoints).
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Query

from api.json_safety import sanitize_json

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

router = APIRouter(prefix="/api/backtest", tags=["reports"])

_ARTIFACTS = {
    "sector-summary": REPO_ROOT / "backtest" / "sector_metrics.json",
    "cross-sectional": REPO_ROOT / "backtest" / "cross_sectional_metrics.json",
    "walk-forward": REPO_ROOT / "backtest" / "walk_forward_results.json",
    "run-summary": REPO_ROOT / "lstm" / "models" / "run_summary.json",
}


@lru_cache(maxsize=None)
def _load_sanitized_at(path_str: str, _mtime_ns: int) -> Any:
    path = Path(path_str)
    with path.open() as f:
        raw = json.load(f)
    return sanitize_json(raw)


def _load_sanitized(path_str: str) -> Any:
    """Cache keyed on (path, mtime) rather than a bare path -- these
    artifacts get regenerated by scripts/refresh_backtests.sh (weekly, see
    api/README.md's Data freshness section) while this API process keeps
    running, so a bare `@lru_cache(maxsize=None)` on the path alone would
    keep serving the pre-refresh file forever until someone restarted the
    server. Only ever a handful of distinct (path, mtime) pairs over this
    process's lifetime, so the cache can't grow unbounded."""
    path = Path(path_str)
    if not path.exists():
        raise HTTPException(status_code=503, detail=f"artifact not found on disk: {path}")
    return _load_sanitized_at(path_str, path.stat().st_mtime_ns)


@router.get("/sector-summary")
def sector_summary() -> Any:
    return _load_sanitized(str(_ARTIFACTS["sector-summary"]))


@router.get("/cross-sectional")
def cross_sectional() -> Any:
    return _load_sanitized(str(_ARTIFACTS["cross-sectional"]))


@router.get("/walk-forward")
def walk_forward() -> Any:
    data = _load_sanitized(str(_ARTIFACTS["walk-forward"]))
    if isinstance(data, dict):
        data = {
            "scope": "semiconductors_only_8_ticker_2024_2026_regime",
            **data,
        }
    return data


@router.get("/run-summary")
def run_summary(variant: str | None = Query(default=None, description="baseline or flux")) -> Any:
    data = _load_sanitized(str(_ARTIFACTS["run-summary"]))
    if variant is not None:
        if variant not in data:
            raise HTTPException(status_code=404, detail=f"unknown variant {variant!r}")
        return {variant: data[variant]}
    return data
